# Generated by Django 3.2.5 on 2021-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.IntegerField(default=1, verbose_name='手机号'),
        ),
    ]
